id: kconfigwidgets
about: KF5 kconfigwidgets
merge: [external/include/kf5.inc]
depends:
  - components/kauth.yml
  - components/kcodecs.yml
  - components/kconfig.yml
  - components/kcolorscheme.yml
  - components/kconfig.yml
  - components/kwidgetsaddons.yml
  - components/kguiaddons.yml
  - components/ki18n.yml
  - components/kwidgetsaddons.yml
build-depends:
  - components/extra-cmake-modules.yml
  - components/perl.yml
  - components/kdoctools.yml
