id: pkg-config
version: 2.2.0
about: Tool for passing the include path and/or library paths to build tools during the configure and make phases of package installations

configure: >-
  -D tests=disabled
sources:
  - https://gitea.treehouse.systems/ariadne/pkgconf/archive/pkgconf-%{version}.tar.gz

depends:
  - components/glibc.yml

post-script: ln -sv pkgconf %{install-root}/usr/bin/pkg-config
