id: gnome-settings-daemon
version: 46.0
about: Daemon responsible for setting various parameters of a GNOME Session

configure: >-
  --buildtype=release
  -Dwwan=false

depends:
  - components/alsa-lib.yml
  - components/colord.yml
  - components/fontconfig.yml
  - components/gcr.yml
  - components/geoclue.yml
  - components/geocode-glib.yml
  - components/gnome/gnome-desktop.yml
  - components/lcms.yml
  - components/ibus.yml
  - components/libcanberra.yml
  - components/libgweather.yml
  - components/libnotify.yml
  - components/librsvg.yml
  - components/libwacom.yml
  - components/pulseaudio.yml
  - components/systemd.yml
  - components/upower.yml
  - components/alsa-lib.yml
  - components/cups.yml
  - components/networkmanager.yml
  - components/nss.yml
  - components/wayland.yml
sources:
  - https://download.gnome.org/sources/gnome-settings-daemon/%{version:2}/gnome-settings-daemon-%{version}.tar.xz
