id: fontconfig
version: 2.13.1
about: |
  Library and support programs used for configuring and customizing font access

depends:
  runtime:
    - freetype

  buildtime:
    - gperf
  
sources:
  - https://www.freedesktop.org/software/fontconfig/release/fontconfig-2.13.1.tar.bz2

packages:
  - id: pkg
    dir: fontconfig-2.13.1
    flags:
      - id: configure
        value: --sysconfdir=/etc

    postscript: |
      install -v -D -m 644 ${FILES}/triggers/fonts.yml -t ${pkgupd_pkgdir}/usr/share/pkgupd/triggers/
    