id: lightdm-gtk-greeter-settings
version: 1.2.2
about: Settings editor for the LightDM GTK+ Greeter

depends:
  - components/gtk4.yml
  - components/py/py-gobject.yml
  - components/py/py-distutils-extra.yml

install: --xfce-integration

sources:
  - https://github.com/Xubuntu/lightdm-gtk-greeter-settings/releases/download/lightdm-gtk-greeter-settings-%{version}/lightdm-gtk-greeter-settings-%{version}.tar.gz
