id: systemsettings
merge: [elements/include/plasma.yml]
about: Plasma systemsettings

depends:
  - components/plasma-workspace.yml
build-depends:
  - components/extra-cmake-modules.yml
  - components/kdoctools.yml
