id: xfce4-settings
version: 4.18.3
about: collection of programs to adjust xfce preferences

configure: >-
  --enable-sound-settings
  --enable-pluggable-dialogs

post-script: |-
  install -vDm0644 /dev/stdin %{install-root}%{libdir}/tmpfiles.d/%{id}.conf << "EOF"
  C %{sysconfdir}/xdg/autostart/xsettingsd.desktop
  EOF
  install -vDm 0644 /dev/stdin %{install-root}/%{sysconfdir}/xdg/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml << "EOF"
  <?xml version="1.0" encoding="UTF-8"?>
  <channel name="xsettings" version="1.0">
    <property name="Net" type="empty">
      <property name="ThemeName" type="string" value="Qogir-Light"/>
      <property name="IconThemeName" type="string" value="Qogir"/>
      <property name="DoubleClickTime" type="int" value="400"/>
      <property name="DoubleClickDistance" type="int" value="5"/>
      <property name="DndDragThreshold" type="int" value="8"/>
      <property name="CursorBlink" type="bool" value="true"/>
      <property name="CursorBlinkTime" type="int" value="1200"/>
      <property name="SoundThemeName" type="string" value="default"/>
      <property name="EnableEventSounds" type="bool" value="false"/>
      <property name="EnableInputFeedbackSounds" type="bool" value="false"/>
    </property>
    <property name="Xft" type="empty">
      <property name="DPI" type="int" value="105"/>
      <property name="Antialias" type="int" value="-1"/>
      <property name="Hinting" type="int" value="-1"/>
      <property name="HintStyle" type="string" value="hintnone"/>
      <property name="RGBA" type="string" value="none"/>
      <!-- <property name="Lcdfilter" type="string" value="none"/> -->
    </property>
    <property name="Gtk" type="empty">
      <property name="CanChangeAccels" type="bool" value="false"/>
      <property name="ColorPalette" type="string" value="black:white:gray50:red:purple:blue:light blue:green:yellow:orange:lavender:brown:goldenrod4:dodger blue:pink:light green:gray10:gray30:gray75:gray90"/>
      <property name="FontName" type="string" value="Noto Sans 11"/>
      <property name="MonospaceFontName" type="string" value="Source Code Pro 11"/>
      <property name="IconSizes" type="string" value=""/>
      <property name="KeyThemeName" type="string" value=""/>
      <property name="ToolbarStyle" type="string" value="icons"/>
      <property name="ToolbarIconSize" type="int" value="3"/>
      <property name="MenuImages" type="bool" value="true"/>
      <property name="ButtonImages" type="bool" value="true"/>
      <property name="MenuBarAccel" type="string" value="F10"/>
      <property name="CursorThemeName" type="string" value="Adwaita"/>
      <property name="CursorThemeSize" type="int" value="0"/>
      <property name="DecorationLayout" type="string" value="menu:minimize,maximize,close"/>
      <property name="DialogsUseHeader" type="bool" value="false"/>
      <property name="TitlebarMiddleClick" type="string" value="lower"/>
    </property>
    <property name="Gdk" type="empty">
      <property name="WindowScalingFactor" type="int" value="1"/>
    </property>
  </channel>
  EOF

depends:
  - components/exo.yml
  - components/garcon.yml
  - components/xfconf.yml
  - components/libcanberra.yml
  - components/libnotify.yml
  - components/x11/libxklavier.yml
  - components/colord.yml
  - components/libinput.yml
  - components/upower.yml
  - components/themes/adwaita-icon-theme.yml
  - components/themes/qogir-gtk-theme.yml
  - components/themes/qogir-icon-theme.yml
  - components/fonts/adobe-source-code-pro-fonts.yml
  - components/fonts/noto.yml
  - components/fonts/noto-cjk.yml
  - components/fonts/noto-emoji.yml
build-time:
  - components/intltool.yml
  - components/x11/xf86-input-libinput.yml
sources:
  - https://archive.xfce.org/src/xfce/xfce4-settings/%{version:1}/xfce4-settings-%{version}.tar.bz2

