id: ostree-config
version: 0.1.0
about: OStree remote and mount configurations

build-depends:
  - components/bash.yml

script: |-
  install -D -m 0644 -t %{install-root}/%{sysconfdir}/pki/ostree/ $AVYOS_FILES/avyos.gpg
  install -D -m 0644 /dev/stdin %{install-root}/%{sysconfdir}/ostree/remotes.d/avyos.conf << "EOF"
  [remote "avyos"]
  url=https://ostree.avyos.dev
  gpg-verify=true
  gpgkeypath=/%{sysconfdir}/pki/ostree//avyos.gpg
  EOF

  install -D -m 0644 /dev/stdin %{install-root}/%{libdir}/tmpfiles.d/ostree.conf << "EOF"
  d /var/log/journal 2755 root systemd-journal -
  d /var/home 0755 root root -
  d /var/roothome 0700 root root -
  d /run/media 0755 root root -
  C /var/roothome/.profile - - - /etc/skel/.profile
  C /var/roothome/.bashrc - - - /etc/skel/.bashrc
  EOF

  install -D -m 0644 /dev/stdin %{install-root}/%{libdir}/systemd/system/home.mount << "EOF"
  [Unit]
  Description=Bind mount of /home
  DefaultDependencies=no
  Before=local-fs.target

  [Mount]
  What=/var/home
  Where=/home
  Type=none
  Options=bind

  [Install]
  WantedBy=local-fs.target
  EOF

  install -D -m 0644 /dev/stdin %{install-root}/%{libdir}/systemd/system/boot.mount << "EOF"
  [Unit]
  Description=Mount OStree boot on /boot
  DefaultDependencies=no
  Before=local-fs.target

  [Mount]
  What=/sysroot/boot
  Where=/boot
  Type=none
  Options=bind

  [Install]
  WantedBy=local-fs.target
  EOF

  install -D -m 0644 /dev/stdin %{install-root}/%{libdir}/systemd/system/root.mount << "EOF"
  [Unit]
  Description=Bind mount of /root
  DefaultDependencies=no
  Before=local-fs.target

  [Mount]
  What=/var/roothome
  Where=/root
  Type=none
  Options=bind

  [Install]
  WantedBy=local-fs.target
  EOF
